services:

  customer-app:
    build:
      context: ./app
    image: customer-app:${APP_VERSION:-5.0}
    container_name: ${APP_NAME:-customer-app-dev}
    ports:
      - "${HOST_PORT:-8081}:5000"
    environment:
      APP_VERSION: "${APP_VERSION:-5.0}"
      ENVIRONMENT: "${ENVIRONMENT:-DEV}"
      DB_HOST: "${DB_NAME:-customer-db-dev}"
      DB_USER: "${DB_USER:-customer}"
      DB_PASSWORD: "${DB_PASSWORD:-customer123}"
      DB_NAME: "${DB_DATABASE:-customerdb}"
    depends_on:
      - customer-db
    networks:
      - customer-network

  customer-db:
    image: mysql:8.0
    container_name: ${DB_NAME:-customer-db-dev}
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-root123}"
      MYSQL_DATABASE: "${DB_DATABASE:-customerdb}"
      MYSQL_USER: "${DB_USER:-customer}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-customer123}"
    volumes:
      - ${DB_VOLUME:-customer-db-dev-data}:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - customer-network

networks:

  customer-network:
    name: ${NETWORK_NAME:-customer-dev-net}

volumes:
  customer-db-dev-data:
    name: ${DB_VOLUME:-customer-db-dev-data}